{% set name = "benten" %}
{% set version = "2021.1.25" %}
{% set sha256 = "1ed60d4fa0a71706a83cf4d74a36ef9c27c1549a8aeef2cdc0309243b5b4003e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabix/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - benten-ls=benten.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cwlformat >=2021.1.5
    - ruamel.yaml ==0.16.12
    - dukpy >=0.2.2

test:
  imports:
    - benten
  commands:
    - benten-ls --help

about:
  home: https://github.com/rabix/benten
  license: Apache-2.0
  license_file: LICENSE
  summary: A language server for Common Workflow Language documents.
  description: |
    benten implements the language server protocol to allow editors like VSCode to provide
    syntax highlighting, autocomplete and other features for editing CWL (Common Workflow Language)
    documents
  doc_url: https://github.com/rabix/benten
  dev_url: https://github.com/rabix/benten

extra:
  recipe-maintainers:
    - pvanheus
